var gui_mouse_x = device_mouse_x_to_gui(0);
var gui_mouse_y = device_mouse_y_to_gui(0);
var is_mouse_x_hovering = gui_mouse_x >= 10 && gui_mouse_x <= 390;
draw_set_color(c_gray);
draw_roundrect(0, 600, 400, 1080, false);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
var is_mouse_on_connect_button = is_mouse_x_hovering && gui_mouse_y >= 610 && gui_mouse_y <= 660;
draw_set_color(is_connected ? (is_mouse_on_connect_button ? c_maroon : c_red) : (is_mouse_on_connect_button ? c_navy : c_blue));
draw_roundrect(10, 610, 390, 660, false);
draw_set_color(c_white);
draw_text(200, 637, is_connected ? "Disconnect" : "Connect");
draw_set_color((is_mouse_x_hovering && gui_mouse_y >= 710 && gui_mouse_y <= 760) ? c_purple : c_dkgray);
draw_roundrect(10, 710, 390, 760, false);
draw_set_color(c_white);
draw_text_transformed(200, 737, is_host ? "Stop Hosing" : "Become Host", 0.8, 0.8);
draw_set_color((is_mouse_x_hovering && gui_mouse_y >= 810 && gui_mouse_y <= 860) ? c_purple : c_dkgray);
draw_roundrect(10, 810, 390, 860, false);
draw_set_color(c_white);
draw_text_transformed(200, 837, "Edit Host IP", 0.8, 0.8);
draw_set_color((is_mouse_x_hovering && gui_mouse_y >= 910 && gui_mouse_y <= 960) ? c_purple : c_dkgray);
draw_roundrect(10, 910, 390, 960, false);
draw_set_color(c_white);
draw_text_transformed(200, 937, "Edit Host Port", 0.7, 0.7);
draw_set_color(c_white);
draw_text_transformed(200, 1030, "F1 to close", 0.5, 0.5, 0);
scr_draw_mouse();
